/* EMulator Studio — Markdown report builder. Produces { md, assets:[{path,blob}] }. */
(function (global) {
  'use strict';
  const { zip, shot } = global.EMU;

  function buildMarkdown(state, sections) {
    const s = sections || {};
    const r = state.inspection;
    const lines = [];
    const push = (...x) => lines.push(...x);

    push('# EMulator Studio — Test Report', '');
    push('- **Generated:** ' + new Date().toISOString());
    push('- **Device:** ' + (state.device ? state.device.name + ' (' + state.device.w + '×' + state.device.h + ' @' + state.device.dpr + 'x' + (state.landscape ? ', landscape' : '') + ')' : '—'));
    if (state.source) push('- **Source:** ' + state.source);
    if (r) {
      push('- **Package:** `' + r.fileName + '` (' + zip.fmtBytes(r.fileSize) + ')');
      push('- **Type:** ' + r.kind.toUpperCase() + (r.runnable ? ' · runnable (hybrid web app)' : ' · inspect-only (native)'));
    }
    push('');

    if (s.meta !== false && r) {
      push('## App metadata', '');
      const m = r.meta;
      const rows = r.kind === 'apk'
        ? [['Name', m.name], ['Package', m.package], ['Version', m.versionName + ' (code ' + m.versionCode + ')'], ['Min SDK', m.minSdk], ['Target SDK', m.targetSdk], ['ABIs', (r.abis || []).join(', ') || '—'], ['Frameworks', (r.frameworks || []).join(', ')]]
        : [['Name', m.name], ['Bundle ID', m.bundleId], ['Version', m.versionName + ' (build ' + m.versionCode + ')'], ['Min iOS', m.minOS], ['Device family', m.deviceFamily || '—'], ['Built with', m.platform || '—'], ['Frameworks', (r.frameworks || []).join(', ')]];
      push('| Field | Value |', '| --- | --- |');
      rows.forEach(([k, v]) => push('| ' + k + ' | ' + (v == null ? '—' : String(v)) + ' |'));
      push('');
    }

    if (s.permissions !== false && r && r.permissions && r.permissions.length) {
      push('## ' + (r.kind === 'apk' ? 'Permissions' : 'Privacy usage') + ' (' + r.permissions.length + ')', '');
      r.permissions.forEach(p => push('- `' + p + '`'));
      push('');
    }

    if (s.files !== false && r && r.summary) {
      push('## Package contents', '');
      push('- **Files:** ' + r.summary.fileCount + ' · **Uncompressed:** ' + zip.fmtBytes(r.summary.totalUncompressed));
      if (r.summary.topDirs.length) { push('', '**Largest directories**', ''); r.summary.topDirs.forEach(([d, sz]) => push('- `' + d + '/` — ' + zip.fmtBytes(sz))); }
      push('');
    }

    const logs = state.logs || [];
    const errs = logs.filter(l => l.level === 'error' || l.level === 'warn');
    if (s.consoleErrors !== false && errs.length) {
      push('## Console — errors & warnings (' + errs.length + ')', '', '```log');
      errs.forEach(l => push('[' + l.level.toUpperCase() + '] ' + l.text));
      push('```', '');
    }
    if (s.consoleAll && logs.length) {
      push('## Console — full log (' + logs.length + ')', '', '```log');
      logs.forEach(l => push('[' + l.level.toUpperCase() + '] ' + l.text));
      push('```', '');
    }

    const net = state.network || [];
    if (s.network && net.length) {
      push('## Network (' + net.length + ')', '', '| Method | Status | ms | URL |', '| --- | --- | --- | --- |');
      net.slice(0, 200).forEach(n => push('| ' + (n.method || 'GET') + ' | ' + (n.status || (n.ok ? 200 : 'ERR')) + ' | ' + (n.ms || '—') + ' | ' + truncate(n.url, 80) + ' |'));
      push('');
    }

    const assets = [];
    const shots = state.screenshots || [];
    if (s.screenshots !== false && shots.length) {
      push('## Screenshots (' + shots.length + ')', '');
      shots.forEach(sh => {
        const path = 'screenshots/' + sh.name;
        assets.push({ path, blob: shot.dataUrlToBlob(sh.dataUrl) });
        push('### ' + (sh.device || 'Screen') + ' — ' + sh.time, '', '![' + sh.name + '](' + path + ')', '');
      });
    }

    if (r && r.notes && r.notes.length) {
      push('## Notes', '');
      r.notes.forEach(n => push('- ' + n));
      push('');
    }

    push('---', '*Generated by EMulator Studio. Native binaries are inspected, not executed; web/PWA & hybrid builds run live in the device frame.*');
    return { md: lines.join('\n'), assets };
  }

  function truncate(s, n) { s = String(s || ''); return s.length > n ? s.slice(0, n - 1) + '…' : s; }

  function downloadText(name, text) {
    const blob = new Blob([text], { type: 'text/markdown' });
    triggerDownload(name, blob);
  }
  function triggerDownload(name, blob) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = name; document.body.appendChild(a); a.click();
    setTimeout(() => { a.remove(); URL.revokeObjectURL(url); }, 1000);
  }

  global.EMU = global.EMU || {};
  global.EMU.report = { buildMarkdown, downloadText, triggerDownload };
})(window);
